apiVersion: v1
kind: ReplicationController
metadata:
  name: server-rc
spec:
  replicas: 3
  selector:
    app: server
  template:
    metadata:
      name: server-pod
      labels:
        app: server
    spec:
      containers:
        - name: server
          image: gcr.io/typed-app-dev/kube-test:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080